# Generated by Django 4.0.8 on 2022-11-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('isbn_number', models.IntegerField()),
                ('publication', models.CharField(max_length=80, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
